language: generic
sudo: true

services:
  - docker

env:
  matrix:
    - TAG=9.3
    - TAG=9.3-contrib
    - TAG=9.4
    - TAG=9.4-contrib
    - TAG=9.5
    - TAG=9.5-contrib
    - TAG=9.6
    - TAG=9.6-contrib

script:
  - make build
  - make test

before_deploy:
  - export DOCKER_CONFIG="${HOME}/.docker"
  - mkdir -p "$DOCKER_CONFIG"
  - openssl aes-256-cbc -K "$DOCKER_CONF_key" -iv "$DOCKER_CONF_iv" -in .docker/config.json.enc -out "${DOCKER_CONFIG}/config.json" -d

deploy:
  provider: script
  skip_cleanup: true
  script: make push
  on:
    branch: master
